/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotFoundRouteImport } from './routes/404'
// Услуги
import { Route as UslugiBuildingRouteImport } from './routes/uslugi/asfaltirovaniye-dorog'
import { Route as UslugiBuildingDvorRouteImport } from './routes/uslugi/asfaltirovaniye-dvorov'
import { Route as UslugiParkovkiRouteImport } from './routes/uslugi/asfaltirovaniye-parkovok'
import { Route as UslugiSntRouteImport } from './routes/uslugi/asfaltirovaniye-snt'
import { Route as UslugiYamochnyRouteImport } from './routes/uslugi/yamochnyy-remont'
import { Route as UslugiPlitkaRouteImport } from './routes/uslugi/trotuarnaya-plitka'
// Геостраницы
import { Route as GeoBalashihaRouteImport } from './routes/asfaltirovanie/balashiha'
import { Route as GeoHimkiRouteImport } from './routes/asfaltirovanie/himki'
import { Route as GeoMytishchiRouteImport } from './routes/asfaltirovanie/mytishchi'
import { Route as GeoKorolevRouteImport } from './routes/asfaltirovanie/korolev'
import { Route as GeoPodolskRouteImport } from './routes/asfaltirovanie/podolsk'
import { Route as GeoLyubertsyRouteImport } from './routes/asfaltirovanie/lyubertsy'
import { Route as GeoKrasnogorskRouteImport } from './routes/asfaltirovanie/krasnogorsk'
import { Route as GeoOdintsvoRouteImport } from './routes/asfaltirovanie/odintsovo'
import { Route as GeoDomodedovoRouteImport } from './routes/asfaltirovanie/domodedovo'
import { Route as GeoIstraRouteImport } from './routes/asfaltirovanie/istra'

const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const PrivacyRoute = PrivacyRouteImport.update({ id: '/privacy', path: '/privacy', getParentRoute: () => rootRouteImport } as any)
const NotFoundRoute = NotFoundRouteImport.update({ id: '/404', path: '/404', getParentRoute: () => rootRouteImport } as any)
// Услуги
const UslugiDorogRoute = UslugiBuildingRouteImport.update({ id: '/uslugi/asfaltirovaniye-dorog', path: '/uslugi/asfaltirovaniye-dorog', getParentRoute: () => rootRouteImport } as any)
const UslugiDvorRoute = UslugiBuildingDvorRouteImport.update({ id: '/uslugi/asfaltirovaniye-dvorov', path: '/uslugi/asfaltirovaniye-dvorov', getParentRoute: () => rootRouteImport } as any)
const UslugiParkovkiRoute = UslugiParkovkiRouteImport.update({ id: '/uslugi/asfaltirovaniye-parkovok', path: '/uslugi/asfaltirovaniye-parkovok', getParentRoute: () => rootRouteImport } as any)
const UslugiSntRoute = UslugiSntRouteImport.update({ id: '/uslugi/asfaltirovaniye-snt', path: '/uslugi/asfaltirovaniye-snt', getParentRoute: () => rootRouteImport } as any)
const UslugiYamochnyRoute = UslugiYamochnyRouteImport.update({ id: '/uslugi/yamochnyy-remont', path: '/uslugi/yamochnyy-remont', getParentRoute: () => rootRouteImport } as any)
const UslugiPlitkaRoute = UslugiPlitkaRouteImport.update({ id: '/uslugi/trotuarnaya-plitka', path: '/uslugi/trotuarnaya-plitka', getParentRoute: () => rootRouteImport } as any)
// Геостраницы
const GeoBalashihaRoute = GeoBalashihaRouteImport.update({ id: '/asfaltirovanie/balashiha', path: '/asfaltirovanie/balashiha', getParentRoute: () => rootRouteImport } as any)
const GeoHimkiRoute = GeoHimkiRouteImport.update({ id: '/asfaltirovanie/himki', path: '/asfaltirovanie/himki', getParentRoute: () => rootRouteImport } as any)
const GeoMytishchiRoute = GeoMytishchiRouteImport.update({ id: '/asfaltirovanie/mytishchi', path: '/asfaltirovanie/mytishchi', getParentRoute: () => rootRouteImport } as any)
const GeoKorolevRoute = GeoKorolevRouteImport.update({ id: '/asfaltirovanie/korolev', path: '/asfaltirovanie/korolev', getParentRoute: () => rootRouteImport } as any)
const GeoPodolskRoute = GeoPodolskRouteImport.update({ id: '/asfaltirovanie/podolsk', path: '/asfaltirovanie/podolsk', getParentRoute: () => rootRouteImport } as any)
const GeoLyubertsyRoute = GeoLyubertsyRouteImport.update({ id: '/asfaltirovanie/lyubertsy', path: '/asfaltirovanie/lyubertsy', getParentRoute: () => rootRouteImport } as any)
const GeoKrasnogorskRoute = GeoKrasnogorskRouteImport.update({ id: '/asfaltirovanie/krasnogorsk', path: '/asfaltirovanie/krasnogorsk', getParentRoute: () => rootRouteImport } as any)
const GeoOdintsvoRoute = GeoOdintsvoRouteImport.update({ id: '/asfaltirovanie/odintsovo', path: '/asfaltirovanie/odintsovo', getParentRoute: () => rootRouteImport } as any)
const GeoDomodedovoRoute = GeoDomodedovoRouteImport.update({ id: '/asfaltirovanie/domodedovo', path: '/asfaltirovanie/domodedovo', getParentRoute: () => rootRouteImport } as any)
const GeoIstraRoute = GeoIstraRouteImport.update({ id: '/asfaltirovanie/istra', path: '/asfaltirovanie/istra', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/404': typeof NotFoundRoute
  '/uslugi/asfaltirovaniye-dorog': typeof UslugiDorogRoute
  '/uslugi/asfaltirovaniye-dvorov': typeof UslugiDvorRoute
  '/uslugi/asfaltirovaniye-parkovok': typeof UslugiParkovkiRoute
  '/uslugi/asfaltirovaniye-snt': typeof UslugiSntRoute
  '/uslugi/yamochnyy-remont': typeof UslugiYamochnyRoute
  '/uslugi/trotuarnaya-plitka': typeof UslugiPlitkaRoute
  '/asfaltirovanie/balashiha': typeof GeoBalashihaRoute
  '/asfaltirovanie/himki': typeof GeoHimkiRoute
  '/asfaltirovanie/mytishchi': typeof GeoMytishchiRoute
  '/asfaltirovanie/korolev': typeof GeoKorolevRoute
  '/asfaltirovanie/podolsk': typeof GeoPodolskRoute
  '/asfaltirovanie/lyubertsy': typeof GeoLyubertsyRoute
  '/asfaltirovanie/krasnogorsk': typeof GeoKrasnogorskRoute
  '/asfaltirovanie/odintsovo': typeof GeoOdintsvoRoute
  '/asfaltirovanie/domodedovo': typeof GeoDomodedovoRoute
  '/asfaltirovanie/istra': typeof GeoIstraRoute
}

export interface FileRoutesByTo extends FileRoutesByFullPath {}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/404': typeof NotFoundRoute
  '/uslugi/asfaltirovaniye-dorog': typeof UslugiDorogRoute
  '/uslugi/asfaltirovaniye-dvorov': typeof UslugiDvorRoute
  '/uslugi/asfaltirovaniye-parkovok': typeof UslugiParkovkiRoute
  '/uslugi/asfaltirovaniye-snt': typeof UslugiSntRoute
  '/uslugi/yamochnyy-remont': typeof UslugiYamochnyRoute
  '/uslugi/trotuarnaya-plitka': typeof UslugiPlitkaRoute
  '/asfaltirovanie/balashiha': typeof GeoBalashihaRoute
  '/asfaltirovanie/himki': typeof GeoHimkiRoute
  '/asfaltirovanie/mytishchi': typeof GeoMytishchiRoute
  '/asfaltirovanie/korolev': typeof GeoKorolevRoute
  '/asfaltirovanie/podolsk': typeof GeoPodolskRoute
  '/asfaltirovanie/lyubertsy': typeof GeoLyubertsyRoute
  '/asfaltirovanie/krasnogorsk': typeof GeoKrasnogorskRoute
  '/asfaltirovanie/odintsovo': typeof GeoOdintsvoRoute
  '/asfaltirovanie/domodedovo': typeof GeoDomodedovoRoute
  '/asfaltirovanie/istra': typeof GeoIstraRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PrivacyRoute: typeof PrivacyRoute
  NotFoundRoute: typeof NotFoundRoute
  UslugiDorogRoute: typeof UslugiDorogRoute
  UslugiDvorRoute: typeof UslugiDvorRoute
  UslugiParkovkiRoute: typeof UslugiParkovkiRoute
  UslugiSntRoute: typeof UslugiSntRoute
  UslugiYamochnyRoute: typeof UslugiYamochnyRoute
  UslugiPlitkaRoute: typeof UslugiPlitkaRoute
  GeoBalashihaRoute: typeof GeoBalashihaRoute
  GeoHimkiRoute: typeof GeoHimkiRoute
  GeoMytishchiRoute: typeof GeoMytishchiRoute
  GeoKorolevRoute: typeof GeoKorolevRoute
  GeoPodolskRoute: typeof GeoPodolskRoute
  GeoLyubertsyRoute: typeof GeoLyubertsyRoute
  GeoKrasnogorskRoute: typeof GeoKrasnogorskRoute
  GeoOdintsvoRoute: typeof GeoOdintsvoRoute
  GeoDomodedovoRoute: typeof GeoDomodedovoRoute
  GeoIstraRoute: typeof GeoIstraRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AdminRoute,
  PrivacyRoute,
  NotFoundRoute,
  UslugiDorogRoute,
  UslugiDvorRoute,
  UslugiParkovkiRoute,
  UslugiSntRoute,
  UslugiYamochnyRoute,
  UslugiPlitkaRoute,
  GeoBalashihaRoute,
  GeoHimkiRoute,
  GeoMytishchiRoute,
  GeoKorolevRoute,
  GeoPodolskRoute,
  GeoLyubertsyRoute,
  GeoKrasnogorskRoute,
  GeoOdintsvoRoute,
  GeoDomodedovoRoute,
  GeoIstraRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
